### ISSUE TITLE
Consider renaming g_hooks to gshg_hooks

### ISSUE THREAD

**Issue by christophherr** [srikat/Genesis-Simple-Hook-Guide#2]
If Genesis Simple Hook Guide and Genesis Visual Hook Guide are active and "Action Hooks" or "Clear"  is clicked, it will trigger both plugins.
http://d.pr/i/WeG6

When g_hooks is renamed, the plugins can co-exist without interfering.
http://d.pr/i/YilO

**Comment by srikat** [comment]
Thanks Christoph. I've included this change in the next commit.
